iter5
Painkiller675/url_shortener_6750 pull request #5
Opened 2024-11-30 20:29 UTC by Painkiller675

use environment variables (SERVER_ADDRESS & BASE_URL), start by hierarchy

2024-12-03 21:51 UTC, avhitrov requested changes
Гонки в сторадже. В остальном всё хорошо.

2024-12-03 21:51 UTC, avhitrov commented on cmd/shortener/main.go
> +		panic(err) // or log.Fatal()???
Принято `log.Fatal`, но не принципиально.

2024-12-03 21:51 UTC, avhitrov commented on internal/repository/repository.go
> +var URLStorage = make(map[string]string) // ALIAS - orURL
Мапа – структура потоконебезопасная. Это означает, что в конкурентной среде (а http-сервер априори является конкурентным приложением, так как открывает по горутине на каждый входящий запрос) любые обращения к ней должны оборачиваться блокировками. В Go для этого существуют мьютексы (sync.Mutex или sync.RWMutex). Кроме того, можно использовать потокозащищенные структуры, вроде sync.Map.

Подробнее: https://t.me/bushigo/24

В данном же случае при множестве одновременных запросов имеем:
```
==================
WARNING: DATA RACE
Write at 0x00c0000881e0 by goroutine 7:
  runtime.mapassign_faststr()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.9.windows-amd64/src/runtime/map_faststr.go:203 +0x0
  github.com/Painkiller675/url_shortener_6750/internal/repository.WriteURL()
      C:/work/src/github.com/Painkiller675/url_shortener_6750/internal/repository/repository.go:12 +0x5b
  github.com/Painkiller675/url_shortener_6750/internal/handlers.CreateShortURLHandler()
      C:/work/src/github.com/Painkiller675/url_shortener_6750/internal/handlers/handlers.go:23 +0x11c
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.9.windows-amd64/src/net/http/server.go:2171 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:459 +0x594
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.9.windows-amd64/src/net/http/server.go:2171 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:73 +0x716
  github.com/go-chi/chi/v5.(*Mux).Mount.func1()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:327 +0x4e5
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.9.windows-amd64/src/net/http/server.go:2171 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:459 +0x594
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.9.windows-amd64/src/net/http/server.go:2171 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:90 +0x69e
  net/http.serverHandler.ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.9.windows-amd64/src/net/http/server.go:3142 +0x2a1
  net/http.(*conn).serve()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.9.windows-amd64/src/net/http/server.go:2044 +0x13c4
  net/http.(*Server).Serve.gowrap3()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.9.windows-amd64/src/net/http/server.go:3290 +0x4f

Previous read at 0x00c0000881e0 by goroutine 28:
  runtime.mapaccess2_faststr()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.9.windows-amd64/src/runtime/map_faststr.go:108 +0x0
  github.com/Painkiller675/url_shortener_6750/internal/repository.GetShortURL()
      C:/work/src/github.com/Painkiller675/url_shortener_6750/internal/repository/repository.go:17 +0x5a
  github.com/Painkiller675/url_shortener_6750/internal/handlers.GetLongURLHandler()
      C:/work/src/github.com/Painkiller675/url_shortener_6750/internal/handlers/handlers.go:45 +0x19b
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.9.windows-amd64/src/net/http/server.go:2171 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:459 +0x594
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.9.windows-amd64/src/net/http/server.go:2171 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:73 +0x716
  github.com/go-chi/chi/v5.(*Mux).Mount.func1()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:327 +0x4e5
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.9.windows-amd64/src/net/http/server.go:2171 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:459 +0x594
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.9.windows-amd64/src/net/http/server.go:2171 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:90 +0x69e
  net/http.serverHandler.ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.9.windows-amd64/src/net/http/server.go:3142 +0x2a1
  net/http.(*conn).serve()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.9.windows-amd64/src/net/http/server.go:2044 +0x13c4
  net/http.(*Server).Serve.gowrap3()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.9.windows-amd64/src/net/http/server.go:3290 +0x4f

Goroutine 7 (running) created at:
  net/http.(*Server).Serve()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.9.windows-amd64/src/net/http/server.go:3290 +0x8ec
  net/http.(*Server).ListenAndServe()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.9.windows-amd64/src/net/http/server.go:3189 +0xbc
  net/http.ListenAndServe()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.9.windows-amd64/src/net/http/server.go:3443 +0x344
  main.main()
      C:/work/src/github.com/Painkiller675/url_shortener_6750/cmd/shortener/main.go:24 +0x23b

Goroutine 28 (running) created at:
  net/http.(*Server).Serve()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.9.windows-amd64/src/net/http/server.go:3290 +0x8ec
  net/http.(*Server).ListenAndServe()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.9.windows-amd64/src/net/http/server.go:3189 +0xbc
  net/http.ListenAndServe()
      C:/Users/ahitr/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.9.windows-amd64/src/net/http/server.go:3443 +0x344
  main.main()
      C:/work/src/github.com/Painkiller675/url_shortener_6750/cmd/shortener/main.go:24 +0x23b
==================
```

2024-12-06 20:20 UTC, Painkiller675 commented on internal/repository/repository.go
> +var URLStorage = make(map[string]string) // ALIAS - orURL
Здравствуйте, скажите, пожалуйста, годится ли этот код? Есть ли смысл оборачивать таким образом методы внутри мапы и что это даёт? Хочу актуальность поддерживать (мы говорили об этом с Вами и Вы посоветовали подход с 2 мапами), может стоит юзать второй мьютекс для второй мапы? 
[repository.txt](https://github.com/user-attachments/files/18043319/repository.txt)

2024-12-09 19:41 UTC, avhitrov commented on internal/repository/repository.go
> +var URLStorage = make(map[string]string) // ALIAS - orURL
Вполне годный код. Одного мьютекса, особенно на данном этапе, более чем достаточно. Возврат ошибок тоже реализован верно. Логирование можно сделать на самом верхнем уровне, но при необходимости вполне допустимо и на более нижних уровнях вызовов функций.

2024-12-09 19:41 UTC, avhitrov approved these changes
Для текущего задания реализация отличная. Аппрув.

2024-12-10 16:34 UTC, merged