Iter9
Painkiller675/url_shortener_6750 pull request #9
Opened 2024-12-24 20:54 UTC by Painkiller675

iter9 save to the file (js). How to correct that the best?

2024-12-24 21:04 UTC, Painkiller675 commented
iter9 сделал супер криво. Не соображу как лучше сделать?

2025-01-02 20:30 UTC, Painkiller675 commented
Подскажите, пожалуйста, нормальная ли структура, старался переделывать по Вашим наставлениям? Дело в том,  что у меня отсутствует возможность пробросить логгер в функции getStorage и saveStorage. Стоит ли эти функции как-то вынести в методы тоже? При этом я вызываю сохранение при каждой записи. Если я вынесу их в методы, то как тогда вызывать это сохранение сносно?

2025-01-02 20:32 UTC, Painkiller675 commented
Также крайне хотелось бы пробросить логгер в gzip middleware. Я действую по схеме создания структуры в пакете с нужными полями для передачи логгера например. Куда его там лучше всего определить? Там я оставил закомментрированную структуру и конструктор, но это всё не то, я так думаю. Спасибо!

2025-01-07 21:33 UTC, avhitrov requested changes
В общем, все хорошо, есть мелкие замечания, пара которых не позволяет пропустить код дальше (fmt и нарушение выставления http-статуса). Кроме того, хотелось бы в дальнейшем НЕ видеть большое количество закомментированного кода. Если он есть в какой-то из версий git, значит, он там остался навсегда, из актуальной весь мусор стоит вычистить.

2025-01-07 21:33 UTC, avhitrov commented on cmd/shortener/main.go
> +	r.Use(gzipMW.GzMW)
Если хочется пробросить логгер в мидлварь в виде объекта, то можно создать структуру
```
type MW struct {
    logger SomeLoggerPackage
}
func NewMW(l SomeLoggerPackage) *MW {
    return &MW{
        logger l,
    }
}
```
, отпочковать от этой структуры все функции мидлвари, инициализировать при старте и в r.Use пробрасывать функции инициализированного объекта типа MW.

А можно тупо от контроллера почковать все мидлвари.

2025-01-07 21:33 UTC, avhitrov commented on internal/controller/controller.go
> +	fmt.Println("BASE URL in CreateNoJS = ", baseURL)
```suggestion
	c.logger.Debug("BASE URL in CreateNoJS = ", baseURL)
```
на этом этапе уже не следует оставлять fmt.

2025-01-07 21:33 UTC, avhitrov commented on internal/controller/controller.go
> +	if err != nil { // TODO: mb I should use status 500 here?
Да, здесь лучше возвращать 500.

2025-01-07 21:33 UTC, avhitrov commented on internal/controller/controller.go
> +	if err != nil {
Вот здесь уже не получится вернуть 500, так как УЖЕ выставлен статус 201. Если в процессе записи тела возикла ошибка, можно только залогировать факт ее выставления. Вроде в остальных хендлерах все сделано грамотно, но стоит проверить.

2025-01-08 13:12 UTC, Painkiller675 commented on cmd/shortener/main.go
> +	r.Use(gzipMW.GzMW)
"Отпочковать" имеется ввиду, что сделать так, чтобы всё вот это: type compressWriter struct {
	w  http.ResponseWriter
	zw *gzip.Writer
}

func newCompressWriter(w http.ResponseWriter) *compressWriter {
	return &compressWriter{
		w:  w,
		zw: gzip.NewWriter(w),
	}
}

func (c *compressWriter) Header() http.Header {
	return c.w.Header()
}

func (c *compressWriter) Write(p []byte) (int, error) {
	return c.zw.Write(p)
}

func (c *compressWriter) WriteHeader(statusCode int) {
	if statusCode < 300 {
		c.w.Header().Set("Content-Encoding", "gzip")
	}
	c.w.WriteHeader(statusCode)
}

// Close закрывает gzip.Writer и досылает все данные из буфера.
func (c *compressWriter) Close() error {
	return c.zw.Close()
}

// compressReader implements interface io.ReadCloser и позволяет прозрачно для сервера
// декомпрессировать получаемые от клиента данные
type compressReader struct {
	r  io.ReadCloser
	zr *gzip.Reader
}

func newCompressReader(r io.ReadCloser) (*compressReader, error) {
	zr, err := gzip.NewReader(r)
	if err != nil {
		return nil, err
	}

	return &compressReader{
		r:  r,
		zr: zr,
	}, nil
}

func (c compressReader) Read(p []byte) (n int, err error) {
	return c.zr.Read(p)
}

func (c *compressReader) Close() error {
	if err := c.r.Close(); err != nil {
		return err
	}
	return c.zr.Close()
}

2025-01-08 13:13 UTC, Painkiller675 commented on cmd/shortener/main.go
> +	r.Use(gzipMW.GzMW)
А также сама middleware функция

2025-01-08 13:13 UTC, Painkiller675 commented on cmd/shortener/main.go
> +	r.Use(gzipMW.GzMW)
Стали методами этой структуры?

2025-01-08 13:13 UTC, Painkiller675 commented on cmd/shortener/main.go
> +	r.Use(gzipMW.GzMW)
> Если хочется пробросить логгер в мидлварь в виде объекта, то можно создать структуру
> 
> ```
> type MW struct {
>     logger SomeLoggerPackage
> }
> func NewMW(l SomeLoggerPackage) *MW {
>     return &MW{
>         logger l,
>     }
> }
> ```
> 
> , отпочковать от этой структуры все функции мидлвари, инициализировать при старте и в r.Use пробрасывать функции инициализированного объекта типа MW.
> 
> А можно тупо от контроллера почковать все мидлвари.

?

2025-01-08 13:21 UTC, Painkiller675 commented on internal/controller/controller.go
> +	fmt.Println("BASE URL in CreateNoJS = ", baseURL)
done

2025-01-08 13:21 UTC, Painkiller675 commented on internal/controller/controller.go
> +	if err != nil { // TODO: mb I should use status 500 here?
done

2025-01-08 13:51 UTC, Painkiller675 commented on cmd/shortener/main.go
> +	r.Use(gzipMW.GzMW)
у меня же middleware сейчас (gzip) является функцией, при этом в ней используются вспомогательные структуры с их методами для сжатия

2025-01-10 18:07 UTC, avhitrov commented on cmd/shortener/main.go
> +	r.Use(gzipMW.GzMW)
Нормально все решено.

2025-01-10 18:07 UTC, avhitrov approved these changes
Все отлично!

2025-01-10 22:43 UTC, merged